# -*- mode: python ; coding: utf-8 -*-
# SortBench v1.1 - Sorting Benchmark Application PyInstaller Spec
# Built by Anurag Chattopadhyay

import os

current_dir = os.path.dirname(os.path.abspath(SPEC))
datas = [
    ('DATASETS/chess.txt', 'DATASETS'),
    ('DATASETS/mushroom.txt', 'DATASETS'),
    ('DATASETS/T10I4D100K.txt', 'DATASETS'),
    ('DATASETS/pumsb_star.txt', 'DATASETS'),
    ('DATASETS/connect.txt', 'DATASETS'),
    ('DATASETS/pumsb.txt', 'DATASETS'),
    ('DATASETS/T40I10D100K.txt', 'DATASETS'),
    ('SORTER-GUI.py', '.'),
    ('countSort.py', '.'),
    ('radixsort.py', '.'),
    ('heapsort.py', '.'),
    ('timsort.py', '.'),
    ('mergesort_n.py', '.'),
    ('quicksort_n.py', '.'),
    ('insertionSort.py', '.'),
    ('selectionsort.py', '.'),
    ('bubble_Sort.py', '.'),
    ('filetolist.py', '.'),
    ('nearlysort.py', '.'),
    ('benchmark.ico', '.'),
]

hiddenimports = [
    'PyQt6.QtCore',
    'PyQt6.QtGui', 
    'PyQt6.QtWidgets',
    'matplotlib',
    'matplotlib.backends',
    'matplotlib.backends.backend_qtagg',
    'matplotlib.backends.backend_qt6agg',
    'matplotlib.figure',
    'matplotlib.colors',
    'matplotlib.pyplot',
    'numpy',
    'xlsxwriter',
    'xlsxwriter.workbook',
    'xlsxwriter.worksheet',
    'xlsxwriter.format',
    'countSort',
    'radixsort',
    'heapsort',
    'timsort',
    'mergesort_n',
    'quicksort_n',
    'insertionSort',
    'selectionsort',
    'bubble_Sort',
    'filetolist',
    'nearlysort',
    'csv',
    'datetime',
    'importlib.util',
    'random',
    'threading',
    'queue',
    'timeit',
    'time',
    'os',
    'sys',
    'pathlib',
    'collections',
]

a = Analysis(
    ['SORTER-GUI.py'],
    pathex=[current_dir],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={
        'matplotlib': {
            'backends': ['Qt6Agg', 'qtagg']
        }
    },
    runtime_hooks=[],
    excludes=[
        'matplotlib.backends.backend_tkagg',
        'matplotlib.backends.backend_gtk3agg',
        'matplotlib.backends.backend_gtk4agg',
        'matplotlib.backends.backend_wxagg',
        'matplotlib.backends.backend_macosx',
        'matplotlib.backends.backend_pdf',
        'matplotlib.backends.backend_ps',
        'matplotlib.backends.backend_svg',
        'tkinter',
        'gtk',
        'wx',
        'PySide2',
        'PySide6',
        'PyQt5',
        'mergesort_m',
        'quicksort_m', 
        'dichotomysort',
        'pytest',
        'unittest',
        'test',
        'tests',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SortBench',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowing_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='benchmark.ico',
    version_info={
        'version': '1.1.0.0',
        'description': 'SortBench - Sorting Benchmark Application',
        'company': 'Developed by Anurag Chattopadhyay',
        'product': 'SortBench',
        'copyright': '© 2025 Anurag Chattopadhyay',
        'file_version': '1.1.0.0',
        'product_version': '1.1.0.0'
    },
    manifest=None,
    uac_admin=False,
    uac_uiaccess=False,
)
